import type { SoundDef, SoundGroupDef } from "./types";

export const SOUND_GROUPS: SoundGroupDef[] = [
  { id: "bass", name: "Bass" },
  { id: "keys", name: "Keys" },
  { id: "strings", name: "Strings" },
  { id: "brass", name: "Brass" },
  { id: "winds", name: "Winds" },
  { id: "lead", name: "Lead" },
  { id: "pad", name: "Pad" },
  { id: "drums", name: "Drums" },
  { id: "fx", name: "Sound Effects" },
];

export const SOUNDS: SoundDef[] = [
  { id: "bass", name: "Sub bass", group: "bass", description: "Round sine bass with a low octave." },
  { id: "bass-acid", name: "Acid bass", group: "bass", description: "Resonant mono bass with a sharp filter." },
  { id: "bass-reese", name: "Reese bass", group: "bass", description: "Wide detuned bass with chorus." },
  { id: "bass-fm", name: "FM bass", group: "bass", description: "Metallic digital low end." },
  { id: "bass-round", name: "Round bass", group: "bass", description: "Warm rounded analog bass." },
  { id: "bass-wobble", name: "Wobble bass", group: "bass", description: "Animated filtered bass pulse." },
  { id: "keys", name: "FM keys", group: "keys", description: "Bell-like electric keys." },
  { id: "pluck", name: "Pluck", group: "keys", description: "Bright synth pluck." },
  { id: "keys-piano", name: "Soft piano", group: "keys", description: "Short mellow piano-style tone." },
  { id: "keys-epiano", name: "E-piano", group: "keys", description: "Warm tremolo electric keys." },
  { id: "keys-organ", name: "Organ", group: "keys", description: "Drawbar-style sustained tone." },
  { id: "strings-ensemble", name: "String ensemble", group: "strings", description: "Layered bowed strings with slow bloom." },
  { id: "strings-pizzicato", name: "Pizzicato", group: "strings", description: "Short plucked orchestral strings." },
  { id: "strings-cello", name: "Cello", group: "strings", description: "Warm low bowed string voice." },
  { id: "strings-synth", name: "Synth strings", group: "strings", description: "Bright analog-style string machine." },
  { id: "brass-section", name: "Brass section", group: "brass", description: "Wide synth brass ensemble." },
  { id: "brass-stab", name: "Brass stab", group: "brass", description: "Fast punchy brass accent." },
  { id: "brass-horn", name: "French horn", group: "brass", description: "Round mellow horn tone." },
  { id: "brass-muted", name: "Muted brass", group: "brass", description: "Nasal filtered mute-style lead." },
  { id: "winds-flute", name: "Flute", group: "winds", description: "Soft airy sine/triangle wind voice." },
  { id: "winds-clarinet", name: "Clarinet", group: "winds", description: "Reedy hollow woodwind tone." },
  { id: "winds-pan", name: "Pan flute", group: "winds", description: "Breathy stepped flute attack." },
  { id: "winds-breath", name: "Breath pipe", group: "winds", description: "Noisy soft wind texture." },
  { id: "lead", name: "Square lead", group: "lead", description: "Focused detuned square lead." },
  { id: "lead-saw", name: "Saw lead", group: "lead", description: "Wide detuned saw, bright and fat." },
  { id: "lead-soft", name: "Soft lead", group: "lead", description: "Rounded triangle lead." },
  { id: "lead-sync", name: "Sync lead", group: "lead", description: "Buzzy hard-sync style lead." },
  { id: "lead-chip", name: "Chip lead", group: "lead", description: "Arcade pulse lead." },
  { id: "lead-brass", name: "Synth brass", group: "lead", description: "Bright brassy stab." },
  { id: "pad", name: "Soft pad", group: "pad", description: "Slow-attack mellow pad." },
  { id: "pad-choir", name: "Choir pad", group: "pad", description: "Breathy vocal-style pad." },
  { id: "pad-glass", name: "Glass pad", group: "pad", description: "Shimmering airy layer." },
  { id: "pad-strings", name: "String pad", group: "pad", description: "Smooth ensemble-style pad." },
  { id: "pad-atmosphere", name: "Atmosphere", group: "pad", description: "Slow hazy texture." },
  { id: "drums", name: "Drum kit", group: "drums", description: "Punchy synthetic kick/snare/hat." },
  { id: "drums-808", name: "808 kit", group: "drums", description: "Long sub kick, snappy snare." },
  { id: "drums-cr78", name: "CR-78 kit", group: "drums", description: "Soft vintage machine kit." },
  { id: "drums-glitch", name: "Glitch kit", group: "drums", description: "Short digital clicks and snaps." },
  { id: "fx-sweep", name: "Noise sweep", group: "fx", description: "Filtered riser/noise accent." },
  { id: "fx-impact", name: "Impact", group: "fx", description: "Low hit with noisy tail." },
  { id: "fx-laser", name: "Laser zap", group: "fx", description: "Descending arcade zap." },
  { id: "fx-riser", name: "Riser", group: "fx", description: "Pitching-up noise and tone build." },
  { id: "fx-downlifter", name: "Downlifter", group: "fx", description: "Falling filtered sweep." },
  { id: "fx-noise-hit", name: "Noise hit", group: "fx", description: "Short bright cinematic hit." },
  { id: "fx-zap", name: "Electric zap", group: "fx", description: "Snappy synthetic zap." },
];
